### ISSUE TITLE
dubbo服务启动方式浅析 | Leeyom的个人站

### ISSUE THREAD

**Issue by wangleeyom** [wangleeyom/blog-comment-system#44]
http://www.leeyom.top/2018/03/07/dubbo-jar-server/ 

 Dubbo是阿里巴巴公司开源的一个高性能优秀的服务框架，使得应用可通过高性能的RPC实现服务的输出和输入功能，可以和Spring框架无缝集成。最近这段时间，参与了公司一个项目的重构，最主要的就是使用Dubbo将其拆分成微服务架构。本篇中不细说如何使用Dubbo进行rpc服务的调用，主要是浅析下基于Dubbo的微服务的打包以及启动方式。

**Comment by traceflight** [comment]
你好，我这两天尝试使用的gitalk，想向您请教一个问题。我添加了gitalk后，一篇文章添加了评论后，博客中的所有文章后面都会出现相同的评论，而且github项目中只有一个issue，请教一下你是怎么做到每个文章一个issue的？

**Comment by wangleeyom** [comment]
> @traceflight
> 你好，我这两天尝试使用的gitalk，想向您请教一个问题。我添加了gitalk后，一篇文章添加了评论后，博客中的所有文章后面都会出现相同的评论，而且github项目中只有一个issue，请教一下你是怎么做到每个文章一个issue的？
在主题配置文件中配置：
```
gitalk:
  enable: true
  clientID: xxx（你自己的）
  clientSecret: xxx(你自己的)
  repo: xxxx(存放评论的仓库)
  owner: traceflight
  admin: traceflight 
  pagerDirection: last
```
